version: '3.9'

services:
  scp_backend:
    build: .
    depends_on:
      - scp_postgres
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app/backend/

  scp_celery-worker:
    build: .
    command: [
        'celery', '-A', 'solving_code_problems', 'worker', '-l', 'INFO', '-E',
    ]
    depends_on:
      - scp_postgres
      - scp_rabbitmq
    env_file:
      - .env.dev
    volumes:
      - ./backend/:/app/backend/


  scp_postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=solving_code_problems
      - POSTGRES_USER=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432
    volumes:
      - scp_pg_data:/var/lib/postgresql/data

  scp_rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
      - 5672
    volumes:
      - scp_rmq_data:/var/lib/rabbitmq

volumes:
  scp_pg_data:
  scp_rmq_data:
